Find center and find angle
Team-501-The-PowerKnights/vision2019 pull request #3
Opened 2019-02-23 16:25 UTC by Matt-Gleich

findCenter and findAngle functions filled in the file image_calculations.py

2019-02-24 16:40 UTC, ionigman-501 requested changes
take a look at comments

2019-02-24 16:40 UTC, ionigman-501 commented on image_calculations.py
> +    pixel_along_diagoal = sqrt(camera_res[0] ** 2 + camera_res[1] ** 2)
The math used here isn't the proper math for a camera FOV. There was a link i posted as a hint in the channel. It's some pretty complex stuff beyond the pythagorean theorem. Take a look at the hints links, and re-work this to get the horizontal FOV coefficient, which you can then multiply the pixel offset by.

2019-02-24 16:40 UTC, ionigman-501 commented on image_calculations.py
> +    m = cv2.moments(cnt)
math needs to be done on m to find the center of mass. m0, m1 etc. look at the hints i linked.

2019-02-24 16:40 UTC, ionigman-501 commented on image_calculations.py
> +camera_degree = 60
Camera diagonal FOV is 60

2019-02-24 18:53 UTC, Matt-Gleich commented
Ok, I will work on these things throughout the day.

2019-02-25 02:02 UTC, Matt-Gleich commented on image_calculations.py
> +    pixel_along_diagoal = sqrt(camera_res[0] ** 2 + camera_res[1] ** 2)
What is the pixel offset?

2019-03-03 20:03 UTC, Matt-Gleich commented
Just filled in both functions and should be all good now. 👍

2019-03-08 23:56 UTC, merged